### ISSUE TITLE
How can I get the dataset?

### ISSUE THREAD

**Issue by hxiaoj** [umass-ml4ed/prompt_distractor_generation_NAACL#2]
how can I get the dataset? I have download the dataset from eedi but i don't know how to process it

**Comment by alexscarlatos** [comment]
Hi! Apologies for the late response. The data files (.csv) should have the following columns:
- `id`: the unique question ID
- `question`: the question text
- `correct_option`: a JSON object containing:
  - `option`: the correct option text
  - `explanation`: the textual solution for the question
- `construct_info`: a JSON object containing:
  - `construct1`: a list for the top-level construct: `[construct ID: int, construct description: str]`
  - `construct2`: a list for the mid-level construct: `[construct ID: int, construct description: str]`
  - `construct3`: a list for the low-level construct: `[construct ID: int, construct description: str]`
- `distractors`: a JSON list of 3 objects (one for each distractor), each containing:
  - `option_idx`: the index of the option in the question (1-4)
  - `option`: the distractor option text
  - `explanation`: the feedback/explanation text for the distractor
  - `proportion`: the percentage of students that chose this option (set to 0 if unknown)
  - `misconception`: the text for the misconception for this distractor (optional, only needed for misconception-based ICL prompts)

You can specify the train and test file paths using the `data.trainFilepath` and `data.testFilepath` command line arguments. Hope that helps!

**Comment by alexscarlatos** [comment]
The data we used in these experiments is private and different from the publicly available Eedi data. You can talk to Eedi if you're interested in discussing if they'd be willing to share with you https://eedi.com/us/contact
